### ISSUE TITLE
Ratings bugs and quirks when adding songs

### ISSUE THREAD

**Issue by zaha0077** [bewa4021/Wasko_CSCI2270_FinalProject#3]
When rating a song when adding one, I found the following:
-You can enter 0 and negative numbers as ratings.
-You can enter numbers larger than five.
-Attempting to enter a letter, word, obscenely large positive or negative number, or a decimal value as a rating causes an infinite loop.

**Comment by bewa4021** [comment]
This should now be fixed. The program is now taking the rating as a string and converting it to an int and checking to make sure it meets requirements. Thanks!
